package woowacourse.kanban

// 보드에 사용된 색상
const val TAG_COLOR = 0xffF3F4F6
const val PROFILE_BG_COLOR = 0xFF888888
const val PROFILE_COLOR = 0xFFFFFFFF
const val CONTENT_COLOR = 0xff4A5565

// 보드에 사용된 색상
// 텍스트 필드 칼럼
const val TEXT_FIELD_BORDER = 0xFF79747E
const val TEXT_FIELD_ERROR = 0xFFB3261E
const val TEXT_FIELD_PLACEHOLDER = 0xFFAAAAAA
const val TEXT_FIELD_HINT = 0xFF49454F
const val HEADER_TEXT = 0xFF364153

// 생성, 취소 버튼
const val PRIMARY_TEXT = 0xFF364153
const val CREATE_BG = 0xFF4F39F6
const val CREATE_BG_ERROR = 0xFFA7A4BC

// 상태 버튼
const val PRIMARY_BORDER = 0xFFE5E7EB
const val STATUS_BORDER_SELECTED = 0xFF1447E6
const val STATUS_BG_SELECTED = 0xFFEFF6FF
const val PRIMARY_SUB_TEXT = 0xFF101828
const val STATUS_TEXT_SELECTED = 0xFF1447E6

// 헤더
const val CLOSE_ICON_TINT = 0xFF6A7282

// 코치 버튼
const val COACH_BORDER_SELECTED = 0xFF615FFF
const val COACH_BG_SELECTED = 0xFFEEF2FF
const val COACH_ICON_TINT = 0xFF838383

// 태스크 생성 페이지
const val COMPLETE_PERCENT = 0xFF6A7282

// 스낵바
const val SNACK_BAR_BG = 0xFF322F35
const val SNACK_BAR_FONT = 0xFFF5EEF7

// 칸반 보드 리스트 - 타이틀 색상
const val STATUS_BG_TO_DO = 0xFF155DFC
const val STATUS_BG_IN_PROGRESS = 0xFFE17100
const val STATUS_BG_DONE = 0xFF00A63E

// 칸반 보드 리스트 - 배경 색상
const val STATUS_LIST_BG_TO_DO = 0xFFEFF6FF
const val STATUS_LIST_BG_IN_PROGRESS = 0xFFFFFBEB
const val STATUS_LIST_BG_DONE = 0xFFF0FDF4

// 칸반 보드 리스트 - 테두리 색상
const val STATUS_LIST_BORDER_TO_DO = 0xFFBEDBFF
const val STATUS_LIST_BORDER_IN_PROGRESS = 0xFFFEE685
const val STATUS_LIST_BORDER_DONE = 0xFFB9F8CF
